### ISSUE TITLE
How can i use this?

### ISSUE THREAD

**Issue by Zaephyyr** [steffalon/dualsense-edge-profile-web-application#1]
Hi i don't know how can i use this, is there any release? thanks

**Comment by steffalon** [comment]
Hello @Zaephyyr ! You can start using it by visiting the following link: https://ds-edge-configurator.com/

ds-edge-configurator.com will be using the latest version from main branch.

**Comment by Zaephyyr** [comment]
I tried it, the dualsense is detected. i seem to be able to save configs but it doesn't work in game. Mapped the back paddles to L3 and R3.

EDIT: Actually it after trying back and forth with the default profile FN+Triangle it seems that the back paddles stop sending inputs on the customized profiles

Thanks for your work anyway! is great having this option without a ps5

**Comment by steffalon** [comment]
@Zaephyyr I assume you are testing it on Windows? It seems that only the Playstation 5 utilizes both paddles natively. I've looked in the Windows game controller settings, and it appears that the paddles don't have an input report. The PS5 reads the controller differently compared to Windows.

You can use DS4Windows, DSX, or other compatible DS edge apps that allow you to map and read the paddles and make them work with your pc games.

**Comment by Zaephyyr** [comment]
Yes, i'm using windows. I tried the same config (through the ps5) and the back paddles work as R3 and L3 in the pc port of Miles morales natively without needing ds4windows

**Comment by steffalon** [comment]
Hello @Zaephyyr ! First, I want to thank you for testing this app. When you were telling me about the ported game supporting paddle inputs, I could test it myself with another PlayStation 5 ported game title to PC. Now, it seems to be fixed. Could you test it once more and let me know if it works for you aswell?

**Comment by Zaephyyr** [comment]
Yeah! Working here on my end too. Amazing work man!
