### ISSUE TITLE
Removing "FN + X, O,  △, □"

### ISSUE THREAD

**Issue by MaestroLiendre** [steffalon/dualsense-edge-profile-web-application#3]
Hey there, first thanks for this great tool as I do not owe a ps5 but I do have a Dualsense Edge. Do you think that could be possible to add the functionality to remove the combination to change profiles with "FN + X, O,  △, □", that would give plenty of room for new configs with steam input or reWASD.

Thanks.

**Comment by steffalon** [comment]
Hi @MaestroLiendre ! Thank you for your comment. I have just added a new feature for clearing controller profile configurations.

https://github.com/steffalon/dualsense-edge-profile-web-application/commit/d4470a87bc3b8e0d1e3f44614cc1263995fd6545
